// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var expression = "2 + 2 * 4";

function tokenize(expression) {
  return expression.split(" ");
}

function matchToken(token) {
  switch (token) {
    case "*" :
        return /* Multiply */1;
    case "+" :
        return /* Add */0;
    default:
      return /* Value */[Belt_Option.getExn(Belt_Int.fromString(token))];
  }
}

function parseTokens(tokens) {
  return Belt_Array.map(tokens, matchToken);
}

function evaluate(expression) {
  return 10;
}

var tokens = expression.split(" ");

console.log(Belt_Array.map(tokens, matchToken));

exports.expression = expression;
exports.tokenize = tokenize;
exports.matchToken = matchToken;
exports.parseTokens = parseTokens;
exports.evaluate = evaluate;
/*  Not a pure module */
